<div class="container" style="width: 100%;">
    <br />
    <div class="row">
        <div class="col-4">
            <a href="/kategorija/novi" class="btn btn-default" style="background-color: #49c1a2; width: 300px; margin-bottom: 20px;">Dodaj novu kategoriju</a>
        </div>
    </div>
    
    
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Naziv</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($podaci as $red) {
                    include 'tablicaStavka.phtml';
                }
             ?>
        </tbody>
    </table>
    <br />
</div>