<div class="container" style="width: 500px;">
  <div class="signup-form">
    <form action="/kategorija/promjeni" method="POST">
  	<h2>Promjenite kategoriju</h2>
  	<hr>
      <div class="form-group">
  		  <label>Naziv kategorije</label>
        <input type="text" class="form-control" id="naziv" name="naziv" value="<?php 
            echo $kategorija->naziv;
            ?>">
      </div>
  	  <div class="form-group">
        <label>Nadređena kategorija</label>
        <select name="nadredena_kategorija" id="nadredena_kategorija" class="form-control">
              <option value="1">Slana jela</option>
              <option value="2">Slatka jela</option>
        </select>
      </div>

  	  <div class="form-group">
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Promjeni"></input>
        <a href="/kategorija/index" class="btn btn-primary btn-block btn-lg" style="background-color: red; text-decoration: none; color: white">Odustani</a>
      </div>

      <div class="text-center"><?php echo $poruka; ?></div>
      <input type="hidden" name="kategorija_ID" value="<?php echo $kategorija->kategorija_ID; ?>"></input>
    </form>
  </div>
</div>