<tr>
    <td>  <?php echo $red->naziv ?> </td>
    <td> <?php echo $red->nadredena_kategorija ?> </td>
    <td>
        <a href="/kategorija/promjena?kategorija_ID=<?php echo $red->kategorija_ID?>"><i title="Promjeni" class="fas fa-edit" style="font-size: 1.2em;"></i></a> 
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->naziv ?> ?');" href="/kategorija/obrisi?kategorija_ID=<?php echo $red->kategorija_ID?>"><i title="Obriši" class="fas fa-trash" style="color: red; font-size: 1.5em;"></i></a>
    </td>
</tr>