<div class="col" style="border: 0.1px solid lightgray; margin-top: 20px;">
    <h1><?php echo $red->ime ?>
    <br /> <?php echo $red->prezime ?></h1>
    <i class="fas fa-circle fa-2x" <?php 
        if(!$red->aktivan) {
            echo 'style="color: red" title="NIJE AKTIVAN"';
        } else {
            echo 'style="color: green" title="AKTIVAN"';
        }
        ?>>
    </i>
    <?php echo $red->email ?>
    <hr />
    <a href="/korisnik/promjena?operater_ID=<?php echo $red->operater_ID ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a> 
    <a onclick="return confirm('Sigurno obrisati <?php echo $red->ime . ' ' . $red->prezime ?> ');" href="/korisnik/obrisi?operater_ID=<?php echo $red->operater_ID ?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>  
</div>
