<div class="container">
<br />
<form action="/recept/promjeni" method="POST" enctype="multipart/form-data">
    <label>Naziv recepta</label>
    <input type="text" class="form-control" id="naziv" name="naziv"
        value="<?php echo $recept->naziv ?>"></input>
<br />
    <div class="form-group">
        <label>Odabrana kategorija</label>
            <select name="kategorija" id="kategorija" class="form-control">
                <?php foreach($kategorije as $kategorija): ?>
                <option <?php
                    if($kategorija->kategorija_ID==$recept->kategorija) {
                    echo 'selected="selected"';
                    } ?> value="<?php echo $kategorija->kategorija_ID ?>">
                    <?php echo $kategorija->naziv ?>
                </option>
                <?php endforeach;?>
            </select>
    </div>

    <div class="row">
        <!-- Slika i priprema -->
        <div class="col-md-8">
            <div class="card mb-4">
                <div style="padding-left: 10px" id="slikaModal" data-reveal>
                    <h4>Dodajte sliku</h4>
                    <input type="file" id="inputImage" name="slika" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
                </div>
                <div class="card-body">
                    <h2 class="card-title">Priprema</h2>
                    <textarea rows="10" cols="100" class="form-control" id="priprema" name="priprema"
                    maxlength="999" style="resize:none"><?php echo $recept->priprema ?></textarea>
                </div>
            </div>
        </div>

        <!-- Sastojci -->
        <div class="col-md-4">
            <div class="card my-4">
                <h5 class="card-header">Sastojci</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <textarea rows="6" cols="40" id="sastojak" name="sastojak"
                            style="resize:none"><?php echo $recept->sastojak ?></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 portfolio-item">
                <input type="submit" class="btn btn-primary btn-block btn-lg" style="background-color: #49c1a2; border: none" value="Promjeni recept"></input>
        </div>
        <div class="col-lg-6 portfolio-item">
            <a href="/recept/index" class="btn btn-primary btn-block btn-lg" style="background-color: red; text-decoration: none; color: white; border: none">Odustani</a>
        </div>
        <input type="hidden" name="recept_ID" value="<?php echo $recept->recept_ID; ?>"></input>
    </div>
</form>
</div>