<div class="container">
<br />
<form action="/recept/promjeni" method="POST">
    <label>Naziv recepta</label>
    <input type="text" class="form-control" id="naziv" name="naziv"
        value="<?php echo $recept->naziv ?>"></input>
<br />
    <div class="form-group">
        <label>Odabrana kategorija</label>
            <select name="kategorija" id="kategorija" class="form-control">
                <?php foreach($kategorije as $kategorija): ?>
                <option <?php
                    if($kategorija->kategorija_ID==$recept->kategorija) {
                    echo 'selected="selected"';
                    } ?> value="<?php echo $kategorija->kategorija_ID ?>">
                    <?php echo $kategorija->naziv ?>
                </option>
                <?php endforeach;?>
            </select>
    </div>

    <div class="row">
        <!-- Slika i priprema -->
        <div class="col-md-8">
            <div class="card mb-4">


                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">Priprema</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                </div>
            </div>
        </div>

        <!-- Sastojci -->
        <div class="col-md-4">
            <div class="card my-4">
                <h5 class="card-header">Sastojci</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>Naziv</li>
                                <li>Naziv</li>
                                <li>Naziv</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 portfolio-item">
            <input type="submit" class="btn btn-primary btn-block btn-lg" style="background-color: #49c1a2; border: none" value="Dodaj novi recept"></input>
        </div>
        <div class="col-lg-6 portfolio-item">
            <a href="/recept/index" class="btn btn-primary btn-block btn-lg" style="background-color: red; text-decoration: none; color: white; border: none">Odustani</a>
        </div>

    </div>
</form>
</div>
