<div class="container" style="width: 500px;">
    <div class="signup-form">
        <form action="/recept/promjeni" method="POST">
            <h2>Dodajte novi recept</h2>
            <hr>
            <div class="form-group">
            	<label>Naziv recepta</label>
                <input type="text" class="form-control" id="naziv" name="naziv"
                    value="<?php echo $recept->naziv ?>">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-block btn-lg" value="Dodaj novi recept"></input>
                <a href="/recept/index" class="btn btn-primary btn-block btn-lg" style="background-color: red; text-decoration: none; color: white">Odustani</a>
            </div>
            <input type="hidden" name="recept_ID" value="<?php echo $recept->recept_ID; ?>"></input>
        </form>
    </div>
</div>