<div class="container" style="width: 100%;">
    <br />
    <form action="/recept/novi" method="POST">
        <div class="row">
            <div class="col-4">
                <select name="kategorija" id="kategorija" class="form-control mr-sm-2">
                    <option value="0">Odaberite kategoriju</option>
                    <?php foreach($kategorije as $kategorija): ?>
                        <option value="<?php echo $kategorija->kategorija_ID ?>">
                            <?php echo $kategorija->naziv ?>
                        </option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="col-7" style="text-align: right">
                <input type="submit" class="btn btn-default"
                style="background-color: #49c1a2; width: 730px; margin-bottom: 20px;"
                value="Dodaj novi recept na odabranu kategoriju">
            </div>
        </div>
    </form>
   
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Naziv</th>
                <th>Kategorija</th>
                <th>Akcija</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($podaci as $red) {
                    include 'tablicaStavka.phtml';
                }
             ?>
        </tbody>
    </table>
    <br />
</div>