<div class="container" style="width: 100%;">
    <br />
    <div class="row">
        <div class="col-7">
            <form class="form-inline" action="/recept/trazi" method="get">
                <input style="width: 550px" class="form-control mr-sm-2" type="text" name="uvjet"
                    id="uvjet"
                    placeholder="Unesite dio naziva recepta..."
                    value="<?php echo isset($_GET['uvjet']) ? $_GET['uvjet'] : '' ?>">
               <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Traži</button>
            </form>
        </div>
        <div class="col-5" style="text-align: right">
            <a href="/recept/novi" class="btn btn-default" style="background-color: #49c1a2; width: 400px; margin-bottom: 20px;">Dodaj novi recept</a>
        </div>
    </div>
   
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Naziv</th>
                <th>Kategorija</th>
                <th>Akcija</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($podaci as $red) {
                    include 'tablicaStavka.phtml';
                }
             ?>
        </tbody>
    </table>
    <br />
</div>