<div class="container" style="width: 500px;">
  <div class="signup-form">
    <form action="/recept/dodajnovi" method="POST">
  	<h2>Dodajte novi recept</h2>
  	<hr>
      <div class="form-group">
  		  <label>Naziv recepta</label>
        <input type="text" class="form-control" id="naziv" name="naziv" value="<?php 
            echo isset($_POST['naziv']) ? $_POST['naziv'] : '' 
            ?>">
      </div>
  	  <div class="form-group">
        <label>Kategorija</label>
        <select name="kategorija" id="kategorija" class="form-control">
          <option value="0">Odaberite kategoriju</option>
          <?php foreach($kategorije as $kategorija): ?>
              <option value="<?php echo $kategorija->kategorija_ID ?>">
                  <?php echo $kategorija->naziv ?>
              </option>
          <?php endforeach;?>
        </select>
      </div>

  	  <div class="form-group">
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Dodaj novi recept"></input>
        <a href="/recept/index" class="btn btn-primary btn-block btn-lg" style="background-color: red; text-decoration: none; color: white">Odustani</a>
      </div>
      <div class="text-center"><?php echo $poruka; ?></div>
    </form>
  </div>
</div>

