<div class="container">

<!-- Naslov recepta -->
<h1 class="mt-4 mb-3">Naslov recepta
</h1>

<!-- Pripadajuća kategorija -->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="index.html">Naziv kategorije</a>
    </li>
    <li class="breadcrumb-item active">Naziv recepta</li>

    <li class="navbar-nav ml-auto">
        <a href="/korisnik/promjena?operater_ID=<?php echo $red->sifra ?>">
        <i title="Promjeni" class="fas fa-edit" style="font-size: 1.5em; padding-right: 5px"></i>
        </a>
    </li>
    <li>
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->ime . ' ' . $red->prezime ?> ');"
            href="/korisnik/obrisi?operater_ID=<?php echo $red->operater_ID ?>">
        <i title="Obriši" class="fas fa-trash" style="color: red; font-size: 1.5em;"></i>
        </a> 
    </li>
</ol>

<div class="row">

  <!-- Div od slike i pripreme -->
  <div class="col-lg-8">

    <!-- Slika -->
    <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

    <hr>

    <!-- Priprema -->
    <h3>Priprema</h3>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

    <blockquote class="blockquote">
      <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
      <footer class="blockquote-footer">Someone famous in
        <cite title="Source Title">Source Title</cite>
      </footer>
    </blockquote>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
  </div>

  <!-- Sidebar Widgets Column -->
  <div class="col-md-4">

    <!-- Sastojci sa stranew -->
    <div class="card my-4">
      <h5 class="card-header">Sastojci</h5>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>Web Design</li>
              <li>HTML</li>
              <li>Freebies</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>
<!-- /.row -->

</div>
<!-- /.container -->