<div class="container">
  <?php 
    foreach($podaci as $red){
        include 'opisStavka.phtml';
    }
    foreach($kategorije as $kategorija) {
      include 'opisStavka.phtml';
    }
  ?>






<div class="row">

  <!-- Div od slike i pripreme -->
  <div class="col-lg-8">

    <!-- Slika -->
    <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

    <hr>

    <!-- Priprema -->
    <h3>Priprema</h3>

    <br />
  </div>

  <!-- Sidebar Widgets Column -->
  <div class="col-md-4">

    <!-- Sastojci sa stranew -->
    <div class="card my-4">
      <h5 class="card-header">Sastojci</h5>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>Naziv</li>
              <li>Naziv</li>
              <li>Naziv</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>
<!-- /.row -->

</div>
<!-- /.container -->