<div class="col-lg-4 col-sm-6 portfolio-item">
    <div class="card h-100">
        <a href="/recept/opis?recept_ID=<?php echo $red->recept_ID ?>"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h3 class="card-title">
                    <a style="text-decoration: none; color: #343a40"
                    href="/recept/opis?recept_ID=<?php echo $red->recept_ID ?>"><?php echo $red->naziv ?></a>
                </h3>
                <p class="card-text"><?php echo $red->kategorija ?></p>
                <p class="card-text">
                    <a href="/recept/promjena?recept_ID=<?php echo $red->recept_ID ?>">
                        <i title="Promjeni" class="fas fa-edit" style="font-size: 1.5em; padding-right: 5px"></i>
                    </a>
                    <a onclick="return confirm('Sigurno obrisati <?php echo $red->naziv ?> ');"
                        href="/recept/obrisi?recept_ID=<?php echo $red->recept_ID ?>">
                        <i title="Obriši" class="fas fa-trash" style="color: red; font-size: 1.5em;"></i>
                    </a>
                </p>
            </div>

    </div>
</div>