<tr>
    <td style="font-size: 1.18em">
        <a style="text-decoration: none" href="#"> 
            <?php echo $red->naziv ?>
        </a>
    </td>

    <td>
        <?php echo $red->kategorija ?> 
    </td>

    <td>
        <a onclick="return confirm('Sigurno obrisati <?php echo $red->naziv ?> ?');" href="/recept/obrisi?recept_ID=<?php echo $red->recept_ID?>"><i title="Obriši" class="fas fa-trash" style="color: red; font-size: 1.5em;"></i></a>
    </td>
</tr>