<div class="container" style="width: 500px;">
  <div class="signup-form">
    <form action="/index/autorizacija" method="POST">
  	<h2>Prijavite se</h2>
  	<hr>
      <div class="form-group">
  		  <label>Email</label>
        <input type="email" class="form-control" id="email" name="email" value="<?php echo 'ivorcelic@gmail.com' ?>" required="required">
      </div>

  	  <div class="form-group">
  		  <label>Lozinka</label>
        <input type="password" class="form-control" id="lozinka" name="lozinka" value="<?php echo 'nema' ?>" required="required">
      </div>

  	  <div class="form-group">
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Prijavi se"></input>
      </div>
    </form>
  	<div class="text-center"><?php echo $poruka; ?></div>
  </div>
</div>