<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Mamine slastice</a>
    <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">Početna</a>
        </li>
        
        <li class="nav-item">
        <?php if(isset($_SESSION['operater'])):?>
          <a class="nav-link" href="/kategorija/index">Kategorije</a> 
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/recept/index">Recepti</a> 
        </li>

        <li class="nav-item">
          <?php if($_SESSION['operater']->uloga==='admin'):?>
            <a class="nav-link" href="/korisnik/index">Korisnici</a>
        </li>
          <?php else: ?>
        <li class="nav-item">
          <a class="nav-link" href="/">O meni</a>
          <?php endif; ?>
          <?php endif; ?>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/index/era">ERA</a>
        </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <?php if(!isset($_SESSION['operater'])): ?>
              <a class="nav-link" href="/index/prijava">Prijava</a>
            <?php else: ?>
              <a class="nav-link" href="/index/odjava">Odjavi |
              <?php echo $_SESSION['operater']->ime . 
              ' ' . $_SESSION['operater']->prezime ?></a>
            <?php endif; ?>
          </li>
  
          <li class="nav-item">
            <?php if(!isset($_SESSION['operater'])): ?>
              <a class="nav-link" href="/index/registracija">Registracija</a>
            <?php endif; ?>
          </li>
        </ul>
    </div>
  </div>
</nav>